version: '3.3'
services:
        build:
                image: openjdk:8-jdk-alpine
                depends_on:
                        - testdb
                links:
                        - 'testdb:db'
                user: "${DOCKER_COMPOSE_RUN_AS_USER}"
                working_dir: /app
                volumes:
                        - .:/app
                        - gradle-dist:/root/.gradle
                environment:
                        - APP_DB_PWD
                        - APP_AUTH_JWT_SECRET

        app:
                image: openjdk:8-jdk-alpine
                depends_on:
                        - db
                links:
                        - 'db:db'
                user: "${DOCKER_COMPOSE_RUN_AS_USER}"
                working_dir: /app
                volumes:
                        - .:/app
                        - gradle-dist:/root/.gradle
                ports:
                        - '8080:8080'
                        - '5005:5005'
                command: ./gradlew bootRun
                environment:
                        - APP_DB_PWD
                        - APP_AUTH_JWT_SECRET

        db:
                image: mysql
                healthcheck:
                  test: ["CMD-SHELL", 'mysqladmin ping']
                  interval: 15s
                  timeout: 5s
                  retries: 10
                volumes:
                        - mysql-data:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD

        testdb:
                image: mysql
                healthcheck:
                  test: ["CMD-SHELL", "mysql --protocol=socket -hlocalhost -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
                  interval: 15s
                  timeout: 5s
                  retries: 10
                environment:
                        - MYSQL_ROOT_PASSWORD

volumes:
        gradle-dist:
                external: false

        mysql-data:
                external: false
